openapi: 3.0.1
info:
  title: spring-rest-docs to OAS
  description: Spring REST Docs 테스트 생성물 생성시 추가생성되는 OAS
  version: 0.0.1-SNAPSHOT
servers:
- url: http://localhost:8080
tags: []
paths:
  /users:
    get:
      tags:
      - users
      operationId: user.getAll
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/users-1906100304'
              examples:
                user.getAll:
                  value: |-
                    [ {
                      "id" : "5e4885e5-0829-447e-a407-ef107522192e",
                      "name" : "jeff"
                    }, {
                      "id" : "94641fce-4345-4180-b893-d99a7cacfeb5",
                      "name" : "justin"
                    }, {
                      "id" : "94641fce-4345-4180-b893-d99a7cacfeb5",
                      "name" : "justin"
                    } ]
    put:
      tags:
      - users
      operationId: user.update
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/users-id103855575'
            examples:
              user.update:
                value: |-
                  {
                    "id" : "a935e972-a1ca-49cf-9a30-1d55c481bcdb",
                    "name" : "SW"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/users-id103855575'
              examples:
                user.update:
                  value: |-
                    {
                      "id" : "a935e972-a1ca-49cf-9a30-1d55c481bcdb",
                      "name" : "SW"
                    }
    post:
      tags:
      - users
      operationId: user.create
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/users-20489308'
            examples:
              user.create:
                value: |-
                  {
                    "name" : "chloe"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/users-id103855575'
              examples:
                user.create:
                  value: |-
                    {
                      "id" : "bb8b2999-6c5b-40bd-8a42-1bc76a549b2c",
                      "name" : "chloe"
                    }
  /users/{id}:
    get:
      tags:
      - users
      operationId: user.getOneById
      parameters:
      - name: id
        in: path
        description: 사용자 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/users-id103855575'
              examples:
                user.getOneById:
                  value: |-
                    {
                      "id" : "71d42995-c0d9-4624-89ef-ee95229c7ba2",
                      "name" : "jeff"
                    }
    delete:
      tags:
      - users
      operationId: user.deleteOneById
      parameters:
      - name: id
        in: path
        description: 사용자 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
components:
  schemas:
    users-1906100304:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            description: 사용자 이름
          id:
            type: string
            description: 사용자 아이디
    users-20489308:
      type: object
      properties:
        name:
          type: string
          description: 사용자 이름
    users-id103855575:
      type: object
      properties:
        name:
          type: string
          description: 사용자 이름
        id:
          type: string
          description: 사용자 아이디
