openapi: 3.0.1
info:
  title: Swagger 문서입니다.
  description: 이 문서는Spring REST Docs 기반으로 생성되었습니다.
  version: 0.0.1-SNAPSHOT
servers:
- url: http://localhost:8080
tags: []
paths:
  /users:
    get:
      tags:
      - users
      operationId: user.getAll
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/users-1906100304'
              examples:
                user.getAll:
                  value: |-
                    [ {
                      "id" : "5349d5a1-5c0b-4bf5-9f4f-b582e8799da2",
                      "name" : "jeff"
                    }, {
                      "id" : "360385d8-2c6c-4e0f-ab29-b4008265b79d",
                      "name" : "justin"
                    }, {
                      "id" : "972b97a6-5ae7-4c17-b0ed-ca4fb4541a23",
                      "name" : "kate"
                    } ]
    put:
      tags:
      - users
      operationId: user.update
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/users-id103855575'
            examples:
              user.update:
                value: |-
                  {
                    "id" : "788518e1-f983-4caa-be32-340e00508b22",
                    "name" : "SW"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/users-id103855575'
              examples:
                user.update:
                  value: |-
                    {
                      "id" : "788518e1-f983-4caa-be32-340e00508b22",
                      "name" : "SW"
                    }
    post:
      tags:
      - users
      operationId: user.create
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/users-20489308'
            examples:
              user.create:
                value: |-
                  {
                    "name" : "chloe"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/users-id103855575'
              examples:
                user.create:
                  value: |-
                    {
                      "id" : "c65a1dc6-9b18-4198-9755-e8365e630a7a",
                      "name" : "chloe"
                    }
  /users/{id}:
    get:
      tags:
      - users
      operationId: user.getOneById
      parameters:
      - name: id
        in: path
        description: 사용자 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/users-id103855575'
              examples:
                user.getOneById:
                  value: |-
                    {
                      "id" : "bdba7938-b35d-4a24-9703-e612cc598a45",
                      "name" : "jeff"
                    }
    delete:
      tags:
      - users
      operationId: user.deleteOneById
      parameters:
      - name: id
        in: path
        description: 사용자 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
components:
  schemas:
    users-1906100304:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            description: 사용자 이름
          id:
            type: string
            description: 사용자 아이디
    users-20489308:
      type: object
      properties:
        name:
          type: string
          description: 사용자 이름
    users-id103855575:
      type: object
      properties:
        name:
          type: string
          description: 사용자 이름
        id:
          type: string
          description: 사용자 아이디
